//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sber_Kvit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_addSet_ResourcePath {
            get {
                return ((string)(this["tb_set_addSet_ResourcePath"]));
            }
            set {
                this["tb_set_addSet_ResourcePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_addSet_ResultPath {
            get {
                return ((string)(this["tb_set_addSet_ResultPath"]));
            }
            set {
                this["tb_set_addSet_ResultPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_req_OrgName {
            get {
                return ((string)(this["tb_set_req_OrgName"]));
            }
            set {
                this["tb_set_req_OrgName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_req_Inn {
            get {
                return ((string)(this["tb_set_req_Inn"]));
            }
            set {
                this["tb_set_req_Inn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_req_Kpp {
            get {
                return ((string)(this["tb_set_req_Kpp"]));
            }
            set {
                this["tb_set_req_Kpp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_req_PayAcc {
            get {
                return ((string)(this["tb_set_req_PayAcc"]));
            }
            set {
                this["tb_set_req_PayAcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_req_Bic {
            get {
                return ((string)(this["tb_set_req_Bic"]));
            }
            set {
                this["tb_set_req_Bic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_req_Bank {
            get {
                return ((string)(this["tb_set_req_Bank"]));
            }
            set {
                this["tb_set_req_Bank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_Fio {
            get {
                return ((string)(this["tb_set_file_Fio"]));
            }
            set {
                this["tb_set_file_Fio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_FioChild {
            get {
                return ((string)(this["tb_set_file_FioChild"]));
            }
            set {
                this["tb_set_file_FioChild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_Nazn {
            get {
                return ((string)(this["tb_set_file_Nazn"]));
            }
            set {
                this["tb_set_file_Nazn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_Kbk {
            get {
                return ((string)(this["tb_set_file_Kbk"]));
            }
            set {
                this["tb_set_file_Kbk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_Oktmo {
            get {
                return ((string)(this["tb_set_file_Oktmo"]));
            }
            set {
                this["tb_set_file_Oktmo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_Summa {
            get {
                return ((string)(this["tb_set_file_Summa"]));
            }
            set {
                this["tb_set_file_Summa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_Period {
            get {
                return ((string)(this["tb_set_file_Period"]));
            }
            set {
                this["tb_set_file_Period"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_ClassNum {
            get {
                return ((string)(this["tb_set_file_ClassNum"]));
            }
            set {
                this["tb_set_file_ClassNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_Group {
            get {
                return ((string)(this["tb_set_file_Group"]));
            }
            set {
                this["tb_set_file_Group"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cb_set_addSet_PrintDateSign {
            get {
                return ((bool)(this["cb_set_addSet_PrintDateSign"]));
            }
            set {
                this["cb_set_addSet_PrintDateSign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int combo_set_addSet_KvitCount {
            get {
                return ((int)(this["combo_set_addSet_KvitCount"]));
            }
            set {
                this["combo_set_addSet_KvitCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int combo_set_addSet_Frame {
            get {
                return ((int)(this["combo_set_addSet_Frame"]));
            }
            set {
                this["combo_set_addSet_Frame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int tb_set_addSet_FontSize {
            get {
                return ((int)(this["tb_set_addSet_FontSize"]));
            }
            set {
                this["tb_set_addSet_FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_addSet_AddInfo {
            get {
                return ((string)(this["tb_set_addSet_AddInfo"]));
            }
            set {
                this["tb_set_addSet_AddInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_FioBar {
            get {
                return ((string)(this["tb_set_file_FioBar"]));
            }
            set {
                this["tb_set_file_FioBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_FioChildBar {
            get {
                return ((string)(this["tb_set_file_FioChildBar"]));
            }
            set {
                this["tb_set_file_FioChildBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_NaznBar {
            get {
                return ((string)(this["tb_set_file_NaznBar"]));
            }
            set {
                this["tb_set_file_NaznBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_ClassNumBar {
            get {
                return ((string)(this["tb_set_file_ClassNumBar"]));
            }
            set {
                this["tb_set_file_ClassNumBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_GroupBar {
            get {
                return ((string)(this["tb_set_file_GroupBar"]));
            }
            set {
                this["tb_set_file_GroupBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_KbkBar {
            get {
                return ((string)(this["tb_set_file_KbkBar"]));
            }
            set {
                this["tb_set_file_KbkBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_OktmoBar {
            get {
                return ((string)(this["tb_set_file_OktmoBar"]));
            }
            set {
                this["tb_set_file_OktmoBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_SummaBar {
            get {
                return ((string)(this["tb_set_file_SummaBar"]));
            }
            set {
                this["tb_set_file_SummaBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_file_PeriodBar {
            get {
                return ((string)(this["tb_set_file_PeriodBar"]));
            }
            set {
                this["tb_set_file_PeriodBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_set_req_Inn_Dep {
            get {
                return ((string)(this["tb_set_req_Inn_Dep"]));
            }
            set {
                this["tb_set_req_Inn_Dep"] = value;
            }
        }
    }
}
